"""empty message

Revision ID: 852ba4f64578
Revises: 
Create Date: 2025-11-17 22:33:38.274614

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '852ba4f64578'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_capital_info',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('trade_date', sa.DateTime(), nullable=True, comment='交易日期'),
    sa.Column('bank_code', sa.String(length=16), nullable=True, comment='银行代码'),
    sa.Column('bank_name', sa.String(length=64), nullable=True, comment='银行名称'),
    sa.Column('bank_type', sa.Integer(), nullable=True, comment='银行类型(1-国有行 2-股份制 3-城商行 4-农商行 5-政策性)'),
    sa.Column('total_deposits', sa.Integer(), nullable=True, comment='存款总额(元)'),
    sa.Column('total_loans', sa.Integer(), nullable=True, comment='贷款总额(元)'),
    sa.Column('non_performing_loan_ratio', sa.Integer(), nullable=True, comment='不良贷款率(×10000)'),
    sa.Column('loan_loss_provision_ratio', sa.Integer(), nullable=True, comment='拨备覆盖率(×10000)'),
    sa.Column('net_interest_margin', sa.Integer(), nullable=True, comment='净息差(×10000)'),
    sa.Column('capital_adequacy_ratio', sa.Integer(), nullable=True, comment='资本充足率(×10000)'),
    sa.Column('tier1_capital_ratio', sa.Integer(), nullable=True, comment='一级资本充足率(×10000)'),
    sa.Column('core_tier1_ratio', sa.Integer(), nullable=True, comment='核心一级资本充足率(×10000)'),
    sa.Column('data_source', sa.Integer(), nullable=True, comment='数据来源(1-银保监会 2-央行 3-银行财报)'),
    sa.Column('data_frequency', sa.Integer(), nullable=True, comment='频率(1-日 2-周 3-月 4-季)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bank_code', 'bank_capital_info', ['bank_code'], unique=False)
    op.create_index('idx_bank_type', 'bank_capital_info', ['bank_type'], unique=False)
    op.create_index('idx_trade_date', 'bank_capital_info', ['trade_date'], unique=False)
    op.create_table('intelligence_information',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('stock_symbol_full', sa.String(length=20), nullable=True, comment='股票代码'),
    sa.Column('news_title', sa.String(length=500), nullable=True, comment='标题'),
    sa.Column('news_content', sa.Text(), nullable=True, comment='内容'),
    sa.Column('news_source', sa.String(length=100), nullable=True, comment='来源'),
    sa.Column('publish_time', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('news_url', sa.String(length=500), nullable=True, comment='新闻链接'),
    sa.Column('impact_direction', sa.Integer(), nullable=True, comment='影响面(-1:负面, 0:中性, 1: 正面)'),
    sa.Column('impact_level', sa.Integer(), nullable=True, comment='影响程度(1:低, 2:中, 3:高)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_publish_time', 'intelligence_information', ['publish_time'], unique=False)
    op.create_index('idx_stock_time', 'intelligence_information', ['stock_symbol_full', 'publish_time'], unique=False)
    op.create_index('idx_title_content', 'intelligence_information', ['news_title'], unique=False)
    op.create_table('sector_capital_flow',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('trade_date', sa.DateTime(), nullable=True, comment='交易日期'),
    sa.Column('sector_code', sa.String(length=32), nullable=True, comment='板块代码'),
    sa.Column('sector_name', sa.String(length=64), nullable=True, comment='板块名称'),
    sa.Column('sector_type', sa.Integer(), nullable=True, comment='板块类型(1行业 2概念 3地区)'),
    sa.Column('main_inflow', sa.Integer(), nullable=True, comment='主力流入(元)'),
    sa.Column('main_outflow', sa.Integer(), nullable=True, comment='主力流出(元)'),
    sa.Column('main_net', sa.Integer(), nullable=True, comment='主力净流入(元)'),
    sa.Column('total_inflow', sa.Integer(), nullable=True, comment='总流入(元)'),
    sa.Column('total_outflow', sa.Integer(), nullable=True, comment='总流出(元)'),
    sa.Column('total_net', sa.Integer(), nullable=True, comment='总净流入(元)'),
    sa.Column('stock_count', sa.Integer(), nullable=True, comment='成分股数量'),
    sa.Column('rise_count', sa.Integer(), nullable=True, comment='上涨家数'),
    sa.Column('fall_count', sa.Integer(), nullable=True, comment='下跌家数'),
    sa.Column('flat_count', sa.Integer(), nullable=True, comment='平盘家数'),
    sa.Column('sector_index', sa.Integer(), nullable=True, comment='板块指数(x100)'),
    sa.Column('change_percent', sa.Integer(), nullable=True, comment='涨跌幅(x100)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_change_percent', 'sector_capital_flow', ['change_percent'], unique=False)
    op.create_index('idx_sector_type', 'sector_capital_flow', ['sector_type'], unique=False)
    op.create_index('idx_trade_date_sector_code', 'sector_capital_flow', ['trade_date', 'sector_code'], unique=False)
    op.create_table('stock_basic_info',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('symbol', sa.String(length=10), nullable=True, comment='股票编号'),
    sa.Column('symbol_full', sa.String(length=20), nullable=True, comment='股票代码'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='股票名称'),
    sa.Column('exchange', sa.String(length=10), nullable=True, comment='交易所'),
    sa.Column('listing_date', sa.DateTime(), nullable=True, comment='上市日期'),
    sa.Column('industry', sa.String(length=50), nullable=True, comment='行业'),
    sa.Column('province', sa.String(length=50), nullable=True, comment='省份'),
    sa.Column('city', sa.String(length=50), nullable=True, comment='城市'),
    sa.Column('company_name', sa.String(length=200), nullable=True, comment='公司全称'),
    sa.Column('english_name', sa.String(length=200), nullable=True, comment='英文名称'),
    sa.Column('former_name', sa.String(length=200), nullable=True, comment='曾用简称'),
    sa.Column('market_type', sa.String(length=20), nullable=True, comment='所属市场'),
    sa.Column('legal_representative', sa.String(length=50), nullable=True, comment='法人代表'),
    sa.Column('registered_capital', sa.String(length=50), nullable=True, comment='注册资金(万元)'),
    sa.Column('establish_date', sa.DateTime(), nullable=True, comment='成立日期'),
    sa.Column('website', sa.String(length=200), nullable=True, comment='官网'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='电子邮箱'),
    sa.Column('telephone', sa.String(length=500), nullable=True, comment='联系电话'),
    sa.Column('fax', sa.String(length=50), nullable=True, comment='传真'),
    sa.Column('registered_address', sa.String(length=500), nullable=True, comment='注册地址'),
    sa.Column('business_address', sa.String(length=500), nullable=True, comment='办公地址'),
    sa.Column('postal_code', sa.String(length=20), nullable=True, comment='邮政编码'),
    sa.Column('main_business', sa.Text(), nullable=True, comment='主营业务'),
    sa.Column('business_scope', sa.Text(), nullable=True, comment='经营范围'),
    sa.Column('company_profile', sa.Text(), nullable=True, comment='机构简介'),
    sa.Column('data_source', sa.String(length=50), nullable=True, comment='数据来源'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', name='uniq_symbol'),
    sa.UniqueConstraint('symbol_full', name='uniq_symbol_full')
    )
    op.create_index('idx_exchange', 'stock_basic_info', ['exchange'], unique=False)
    op.create_index('idx_industry', 'stock_basic_info', ['industry'], unique=False)
    op.create_index('idx_listing_date', 'stock_basic_info', ['listing_date'], unique=False)
    op.create_index('idx_province', 'stock_basic_info', ['province'], unique=False)
    op.create_table('stock_capital_flow',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('trade_date', sa.DateTime(), nullable=True, comment='交易日期'),
    sa.Column('stock_symbol_full', sa.String(length=16), nullable=True, comment='股票代码(如 600519.SZ)'),
    sa.Column('exchange', sa.String(length=8), nullable=True, comment='交易所(SH-上交所 SZ-深交所 BJ-北交所)'),
    sa.Column('main_inflow', sa.Integer(), nullable=True, comment='主力流入(元)'),
    sa.Column('main_outflow', sa.Integer(), nullable=True, comment='主力流出(元)'),
    sa.Column('main_net', sa.Integer(), nullable=True, comment='主力净流入(元)'),
    sa.Column('retail_inflow', sa.Integer(), nullable=True, comment='散户流入(元)'),
    sa.Column('retail_outflow', sa.Integer(), nullable=True, comment='散户流出(元)'),
    sa.Column('retail_net', sa.Integer(), nullable=True, comment='散户净流入(元)'),
    sa.Column('total_inflow', sa.Integer(), nullable=True, comment='总流入(元)'),
    sa.Column('total_outflow', sa.Integer(), nullable=True, comment='总流出(元)'),
    sa.Column('total_net', sa.Integer(), nullable=True, comment='总净流入(元)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symbol', 'stock_capital_flow', ['stock_symbol_full'], unique=False)
    op.create_index('idx_trade_date', 'stock_capital_flow', ['trade_date'], unique=False)
    op.create_table('stock_daily_info',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('stock_symbol_full', sa.String(length=20), nullable=True, comment='股票代码'),
    sa.Column('trade_date', sa.DateTime(), nullable=True, comment='交易日期'),
    sa.Column('open_price', sa.Integer(), nullable=True, comment='开盘价(分)'),
    sa.Column('close_price', sa.Integer(), nullable=True, comment='收盘价(分)'),
    sa.Column('high_price', sa.Integer(), nullable=True, comment='最高价(分)'),
    sa.Column('low_price', sa.Integer(), nullable=True, comment='最低价(分)'),
    sa.Column('volume', sa.Integer(), nullable=True, comment='成交量(股)'),
    sa.Column('turnover', sa.Integer(), nullable=True, comment='成交额(分)'),
    sa.Column('change_amount', sa.Integer(), nullable=True, comment='涨跌额(分)'),
    sa.Column('change_rate', sa.Integer(), nullable=True, comment='涨跌幅'),
    sa.Column('pe_ratio', sa.Integer(), nullable=True, comment='市盈率'),
    sa.Column('pb_ratio', sa.Integer(), nullable=True, comment='市净率'),
    sa.Column('market_cap', sa.Integer(), nullable=True, comment='总市值(分)'),
    sa.Column('circulating_market_cap', sa.Integer(), nullable=True, comment='流通市值(分)'),
    sa.Column('turnover_rate', sa.Integer(), nullable=True, comment='换手率'),
    sa.Column('bid_price1', sa.Integer(), nullable=True, comment='买一价(分)'),
    sa.Column('bid_price2', sa.Integer(), nullable=True, comment='买二价(分)'),
    sa.Column('bid_price3', sa.Integer(), nullable=True, comment='买三价(分)'),
    sa.Column('bid_price4', sa.Integer(), nullable=True, comment='买四价(分)'),
    sa.Column('bid_price5', sa.Integer(), nullable=True, comment='买五价(分)'),
    sa.Column('bid_volume1', sa.Integer(), nullable=True, comment='买一量(股)'),
    sa.Column('bid_volume2', sa.Integer(), nullable=True, comment='买二量(股)'),
    sa.Column('bid_volume3', sa.Integer(), nullable=True, comment='买三量(股)'),
    sa.Column('bid_volume4', sa.Integer(), nullable=True, comment='买四量(股)'),
    sa.Column('bid_volume5', sa.Integer(), nullable=True, comment='买五量(股)'),
    sa.Column('ask_price1', sa.Integer(), nullable=True, comment='卖一价(分)'),
    sa.Column('ask_price2', sa.Integer(), nullable=True, comment='卖二价(分)'),
    sa.Column('ask_price3', sa.Integer(), nullable=True, comment='卖三价(分)'),
    sa.Column('ask_price4', sa.Integer(), nullable=True, comment='卖四价(分)'),
    sa.Column('ask_price5', sa.Integer(), nullable=True, comment='卖五价(分)'),
    sa.Column('ask_volume1', sa.Integer(), nullable=True, comment='卖一量(股)'),
    sa.Column('ask_volume2', sa.Integer(), nullable=True, comment='卖二量(股)'),
    sa.Column('ask_volume3', sa.Integer(), nullable=True, comment='卖三量(股)'),
    sa.Column('ask_volume4', sa.Integer(), nullable=True, comment='卖四量(股)'),
    sa.Column('ask_volume5', sa.Integer(), nullable=True, comment='卖五量(股)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_symbol', 'stock_daily_info', ['stock_symbol_full'], unique=False)
    op.create_index('idx_trade_date', 'stock_daily_info', ['trade_date'], unique=False)
    op.create_table('stock_daily_recommendation',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('stock_symbol_full', sa.String(length=20), nullable=True, comment='股票代码'),
    sa.Column('recommend_date', sa.DateTime(), nullable=True, comment='推荐日期'),
    sa.Column('recommend_level', sa.Integer(), nullable=True, comment='推荐等级(1:强烈推荐 2:推荐 3:中性 4:谨慎 5:卖出)'),
    sa.Column('price', sa.Integer(), nullable=True, comment='当前价(分)'),
    sa.Column('target_price', sa.Integer(), nullable=True, comment='目标价(分)'),
    sa.Column('recommend_reason', sa.Text(), nullable=True, comment='推荐理由'),
    sa.Column('analyst', sa.String(length=100), nullable=True, comment='分析师'),
    sa.Column('institution', sa.String(length=100), nullable=True, comment='机构名称'),
    sa.Column('risk_level', sa.Text(), nullable=True, comment='风险等级'),
    sa.Column('validity_period', sa.Integer(), nullable=True, comment='有效期(天)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recommend_date', 'stock_daily_recommendation', ['recommend_date'], unique=False)
    op.create_index('idx_stock_date', 'stock_daily_recommendation', ['stock_symbol_full', 'recommend_date'], unique=False)
    op.create_table('stock_financial_report',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('file_id', sa.Integer(), nullable=True, comment='文件主键'),
    sa.Column('stock_symbol_full', sa.String(length=20), nullable=True, comment='股票代码'),
    sa.Column('report_date', sa.DateTime(), nullable=True, comment='报告期'),
    sa.Column('report_type', sa.Integer(), nullable=True, comment='报告类型(1:一季度, 2:年中, 3:三季度, 4:年终)'),
    sa.Column('total_revenue', sa.Integer(), nullable=True, comment='营业收入（分）'),
    sa.Column('net_profit', sa.Integer(), nullable=True, comment='净利润（分）'),
    sa.Column('total_assets', sa.Integer(), nullable=True, comment='总资产（分）'),
    sa.Column('total_liabilities', sa.Integer(), nullable=True, comment='总负债（分）'),
    sa.Column('net_assets', sa.Integer(), nullable=True, comment='净资产（分）'),
    sa.Column('eps', sa.Integer(), nullable=True, comment='每股收益（分）'),
    sa.Column('roe', sa.Integer(), nullable=True, comment='净资产收益率'),
    sa.Column('gross_profit_margin', sa.Integer(), nullable=True, comment='毛利率'),
    sa.Column('report_source', sa.String(length=100), nullable=True, comment='报告来源'),
    sa.Column('earnings_announcement_date', sa.DateTime(), nullable=True, comment='预约披露日期'),
    sa.Column('published_date', sa.DateTime(), nullable=True, comment='发布日期'),
    sa.Column('comment', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_date', 'stock_financial_report', ['stock_symbol_full', 'report_date'], unique=False)
    op.create_table('stock_holder_info',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('stock_symbol_full', sa.String(length=20), nullable=True, comment='股票代码'),
    sa.Column('holder_name', sa.String(length=200), nullable=True, comment='股东名称'),
    sa.Column('holder_info', sa.String(length=512), nullable=True, comment='股东信息'),
    sa.Column('holder_type', sa.Integer(), nullable=True, comment='股东类型(1:机构, 2:个人, 3:基金, 4:券商, 5:保险, 6:其他)'),
    sa.Column('share_amount', sa.Integer(), nullable=True, comment='持股数量'),
    sa.Column('share_ratio', sa.Integer(), nullable=True, comment='持股比例'),
    sa.Column('change_amount', sa.Integer(), nullable=True, comment='持股变动数量'),
    sa.Column('change_type', sa.Integer(), nullable=True, comment='变动类型(1:增持, 2:减持, 3:不变, 4:新进)'),
    sa.Column('report_date', sa.DateTime(), nullable=True, comment='报告日期'),
    sa.Column('is_top_ten', sa.Integer(), nullable=True, comment='是否十大股东'),
    sa.Column('ranking', sa.Integer(), nullable=True, comment='股东排名'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_holder', 'stock_holder_info', ['holder_name'], unique=False)
    op.create_index('idx_stock_date', 'stock_holder_info', ['stock_symbol_full', 'report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stock_date', table_name='stock_holder_info')
    op.drop_index('idx_holder', table_name='stock_holder_info')
    op.drop_table('stock_holder_info')
    op.drop_index('idx_stock_date', table_name='stock_financial_report')
    op.drop_table('stock_financial_report')
    op.drop_index('idx_stock_date', table_name='stock_daily_recommendation')
    op.drop_index('idx_recommend_date', table_name='stock_daily_recommendation')
    op.drop_table('stock_daily_recommendation')
    op.drop_index('idx_trade_date', table_name='stock_daily_info')
    op.drop_index('idx_stock_symbol', table_name='stock_daily_info')
    op.drop_table('stock_daily_info')
    op.drop_index('idx_trade_date', table_name='stock_capital_flow')
    op.drop_index('idx_symbol', table_name='stock_capital_flow')
    op.drop_table('stock_capital_flow')
    op.drop_index('idx_province', table_name='stock_basic_info')
    op.drop_index('idx_listing_date', table_name='stock_basic_info')
    op.drop_index('idx_industry', table_name='stock_basic_info')
    op.drop_index('idx_exchange', table_name='stock_basic_info')
    op.drop_table('stock_basic_info')
    op.drop_index('idx_trade_date_sector_code', table_name='sector_capital_flow')
    op.drop_index('idx_sector_type', table_name='sector_capital_flow')
    op.drop_index('idx_change_percent', table_name='sector_capital_flow')
    op.drop_table('sector_capital_flow')
    op.drop_index('idx_title_content', table_name='intelligence_information')
    op.drop_index('idx_stock_time', table_name='intelligence_information')
    op.drop_index('idx_publish_time', table_name='intelligence_information')
    op.drop_table('intelligence_information')
    op.drop_index('idx_trade_date', table_name='bank_capital_info')
    op.drop_index('idx_bank_type', table_name='bank_capital_info')
    op.drop_index('idx_bank_code', table_name='bank_capital_info')
    op.drop_table('bank_capital_info')
    # ### end Alembic commands ###
